# Generated by Django 4.2.13 on 2024-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_logo_url', models.TextField()),
                ('event_name', models.CharField(max_length=305)),
                ('event_start_date', models.CharField(max_length=55)),
                ('event_end_date', models.CharField(max_length=35)),
                ('event_venue', models.CharField(max_length=35)),
                ('event_country', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_url', models.TextField()),
            ],
        ),
    ]
