# Generated by Django 4.2.13 on 2024-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('person_city', models.CharField(max_length=50)),
                ('person_state', models.CharField(max_length=50)),
                ('person_country', models.CharField(max_length=50)),
                ('email_pattern', models.CharField(max_length=100)),
                ('homepage_base_url', models.CharField(max_length=150)),
                ('duration_in_current_job', models.CharField(max_length=300)),
                ('duration_in_current_company', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='event_info',
        ),
    ]
